-- 1) CREATE DATABASE
DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_database WHERE datname = 'AccountManager'
    ) THEN
        CREATE DATABASE "AccountManager";
    END IF;
END
$$;

-- 2) SPAJANJE NA BAZU
\connect "AccountManager";


-- 3) CREATE TABLES, PROCEDURES, VIEWS, TRIGGERS, ETC.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE roles (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(20) NOT NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY ("Id")
);

CREATE TABLE users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(200) NOT NULL,
    "Password" text NOT NULL,
    "RoleId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_users_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE RESTRICT
);

CREATE TABLE accounts (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "DateOfBirth" date NOT NULL,
    "Address" character varying(300) NOT NULL,
    CONSTRAINT "PK_accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_accounts_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

INSERT INTO roles ("Id", "Name")
VALUES (1, 'User');
INSERT INTO roles ("Id", "Name")
VALUES (2, 'Admin');

CREATE UNIQUE INDEX "IX_accounts_UserId" ON accounts ("UserId");

CREATE UNIQUE INDEX "IX_roles_Name" ON roles ("Name");

CREATE UNIQUE INDEX "IX_users_Email" ON users ("Email");

CREATE INDEX "IX_users_RoleId" ON users ("RoleId");

CREATE TABLE account_audit_logs (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" integer,
    "UserId" integer,
    "Action" text NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "OldData" text,
    "NewData" text,
    CONSTRAINT "PK_account_audit_logs" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_account_audit_logs_AccountId" ON account_audit_logs ("AccountId");

CREATE INDEX "IX_account_audit_logs_UserId" ON account_audit_logs ("UserId");


CREATE OR REPLACE FUNCTION user_has_account(p_user_id integer)
RETURNS boolean
LANGUAGE sql
AS $$
    SELECT EXISTS (
        SELECT 1 FROM accounts WHERE "UserId" = p_user_id
    );
$$;



CREATE OR REPLACE FUNCTION fn_account_audit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO account_audit_logs("AccountId", "UserId", "Action", "ChangedAt", "OldData", "NewData")
        VALUES (NEW."Id", NEW."UserId", 'INSERT', now(), NULL, row_to_json(NEW)::text);
        RETURN NEW;

    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO account_audit_logs("AccountId", "UserId", "Action", "ChangedAt", "OldData", "NewData")
        VALUES (NEW."Id", NEW."UserId", 'UPDATE', now(), row_to_json(OLD)::text, row_to_json(NEW)::text);
        RETURN NEW;

    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO account_audit_logs("AccountId", "UserId", "Action", "ChangedAt", "OldData", "NewData")
        VALUES (OLD."Id", OLD."UserId", 'DELETE', now(), row_to_json(OLD)::text, NULL);
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$;



DROP TRIGGER IF EXISTS trg_account_audit ON accounts;

CREATE TRIGGER trg_account_audit
AFTER INSERT OR UPDATE OR DELETE ON accounts
FOR EACH ROW
EXECUTE FUNCTION fn_account_audit();



CREATE OR REPLACE VIEW vw_admin_accounts AS
SELECT
    a."Id"           AS "AccountId",
    a."UserId"       AS "UserId",
    u."Email"        AS "UserEmail",
    r."Name"         AS "UserRole",
    a."FirstName"    AS "FirstName",
    a."LastName"     AS "LastName",
    a."DateOfBirth"  AS "DateOfBirth",
    a."Address"      AS "Address"
FROM accounts a
JOIN users u ON u."Id" = a."UserId"
JOIN roles r ON r."Id" = u."RoleId";



CREATE OR REPLACE PROCEDURE sp_create_account(
    IN p_user_id integer,
    IN p_first_name text,
    IN p_last_name text,
    IN p_date_of_birth date,
    IN p_address text,
    OUT new_account_id integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF user_has_account(p_user_id) THEN
        RAISE EXCEPTION 'Account already exists for userId=%', p_user_id
            USING ERRCODE = 'P0001';
    END IF;

    INSERT INTO accounts ("UserId", "FirstName", "LastName", "DateOfBirth", "Address")
    VALUES (p_user_id, p_first_name, p_last_name, p_date_of_birth, p_address)
    RETURNING "Id" INTO new_account_id;
END;
$$;


SELECT setval(
    pg_get_serial_sequence('roles', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM roles) + 1,
        nextval(pg_get_serial_sequence('roles', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260116081943_InitialAllInOne', '9.0.10');

COMMIT;

